import { StyleSheet, StatusBar, Platform } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0D0A19',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  container: {
    flex: 1,
    backgroundColor: '#0D0A19',
  },
  stickyHeader: {
    backgroundColor: '#0D0A19',
    elevation: 10,
  },
  scrollContainer: {
    paddingBottom: 100,
  },
  coinInfoStyle: {
    paddingTop: 20,
    paddingHorizontal: 15,
    flexDirection: 'column',
    alignItems: 'center',
  },
  priceStyle: {
    color: 'white',
    fontSize: 45,
    fontWeight: '500',
    fontFamily: 'Quicksand_600',
    maxWidth: '100%',
    alignSelf: 'center',
  },
  coinChangeValStyle: {
    fontSize: 18,
    fontWeight: '400',
    fontFamily: 'Quicksand_400Regular',
    color: 'black',
    borderRadius: 5,
  },
  changeValContainer: {
    paddingHorizontal: 10,
    borderRadius: 5,
    elevation: 30,
    shadowColor: 'white',
  },
  button: {
    flex: 1,
    margin: 6,
    backgroundColor: '#2b1f4d',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#6C63FF',
    shadowRadius: 10,
    elevation: 10,
    paddingVertical: 12,
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 10,
    marginBottom: 20,
  },
  graphBox: {
    marginTop: 20,
    width: '100%',
    height: 250,
    borderColor: 'white',
    borderWidth: 2,
  },
  miniGraphBox: {
    marginTop: 10,
    alignSelf: 'center',
    width: '90%',
    height: 50,
    borderColor: 'white',
    borderWidth: 2,
  },
  coinExtraDetails: {
    flexDirection: 'column',
  },
  coinDetailsTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    fontFamily: 'Quicksand_600SemiBold',
    color: '#EEEEEE',
    marginVertical: 12,
    marginLeft: 20,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#1C1B2A',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    marginVertical: 6,
    marginHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  label: {
    color: '#AAAAAA',
    fontSize: 15,
    fontWeight: '500',
    fontFamily: 'Quicksand_400Regular',
    flex: 1,
  },
  value: {
    color: 'white',
    fontSize: 15,
    fontWeight: '600',
    fontFamily: 'Quicksand_600SemiBold',
    textAlign: 'right',
    flex: 1,
  },
  
});

export default styles;
